### PR TITLE
Refreshed front page, copy, css & html to better inspire visitors to the mission of the project. Also fixed some deprecation errors due to old hugo configuration.

### PR DESCRIPTION
**Pull request by sebstrgg**

### CODE REVIEW

**Comment by bluecmd** [comment]
Initial quick scan: looks great! Thanks a bunch! 

Commenting to note that the public/ folder shouldn't be `git add`ed, it's pushed automatically to another branch when generated.

**Comment by sebstrgg** [comment]
> Initial quick scan: looks great! Thanks a bunch!
> 
> Commenting to note that the public/ folder shouldn't be `git add`ed, it's pushed automatically to another branch when generated.

Yup, great you noticed. Totally missed out on that one, even though I really tried to remember from the readme :-)

**Comment by sebstrgg** [comment]
Just made another update according to feedback to re-stylize the carousel hero for a more refreshed look, highlighting the bg image in a better way and converted my previous placeholder-button to a real one. Also added a new section for IX locations to better highlight all physical locations and smashed a few css bugs.

Enjoy!

**Review by fyx — APPROVED** [review]
Looks awesome, well done!

**Comment by dal00** [comment]
Great work but the IXP locations links are messed up a little. Obe Kista Gate has a link to our Stockholm IXP instead of the OBE facility. And you have omitted links to the actual IXP in Gothenburg and Malmö. Double check the links we have on the current live page and use those, then I we're probably good.

I think the most important links are the three ix links for Stockholm, Göteborg and Malmö, those are the ones that should be emphasized or easy to find.

**Comment by sebstrgg** [comment]
> Great work but the IXP locations links are messed up a little. Obe Kista Gate has a link to our Stockholm IXP instead of the OBE facility. And you have omitted links to the actual IXP in Gothenburg and Malmö. Double check the links we have on the current live page and use those, then I we're probably good.
> 
> I think the most important links are the three ix links for Stockholm, Göteborg and Malmö, those are the ones that should be emphasized or easy to find.

Fixed the links, found a typo in contact page, updated footer to improve site navigation and promote social media better.

**Comment by dal00** [comment]
I think we're getting there. We could merge this if you feel ready for it now. I still would like some more changes if you're up to it. But that would be fine in a new PR later.

**Review by dal00 — APPROVED** [review]

**Comment by sebstrgg** [comment]
> I think we're getting there. We could merge this if you feel ready for it now. I still would like some more changes if you're up to it. But that would be fine in a new PR later.

Absolutely, there’s plenty more I think needs to be done as well. Let’s have a chat about future changes soon :)

**Pull request merged**
